[package]
name = "pawmodoro"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
anyhow = "1.0.102"
env_logger = "0.11.10"
interprocess = { version = "2.4.2", features = ["tokio"] }


[[bin]]
name = "pawmodoro"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"
